// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Segurança: por padrão, rodar SOMENTE o seed de operadoras (não cria dados demo)
    seed: "tsx prisma/seed-operadoras.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
