/**
 * Carrega os secrets do AWS Secrets Manager e escreve em .env.secrets
 * para ser usado durante o build do Next.js.
 *
 * O Next.js lê automaticamente .env e .env.local, mas não arquivos customizados.
 * Por isso este script escreve em .env.local que tem prioridade sobre .env.
 *
 * Uso:
 *   NODE_ENV=production npx tsx scripts/load-secrets-env.ts
 *   next build   (vai ler .env.local automaticamente)
 */
import {
  SecretsManagerClient,
  GetSecretValueCommand,
} from "@aws-sdk/client-secrets-manager";
import { writeFileSync, existsSync, readFileSync } from "fs";
import { resolve } from "path";

const SECRET_NAME = process.env.AWS_SECRET_NAME || "prontivus/production";
const REGION = process.env.AWS_REGION || "sa-east-1";
const ENV_LOCAL_PATH = resolve(__dirname, "../../.env.local");

async function main() {
  if (process.env.NODE_ENV !== "production") {
    console.log("[pre-build] Ambiente de desenvolvimento — pulando.");
    process.exit(0);
  }

  console.log(`[pre-build] Carregando secrets de '${SECRET_NAME}' (${REGION})...`);

  const client = new SecretsManagerClient({ region: REGION });
  const command = new GetSecretValueCommand({ SecretId: SECRET_NAME });
  const response = await client.send(command);

  if (!response.SecretString) {
    throw new Error("Secret está vazio");
  }

  const secrets: Record<string, string> = JSON.parse(response.SecretString);

  // Ler .env.local existente (se houver) para preservar variáveis locais
  let existingVars: Record<string, string> = {};
  if (existsSync(ENV_LOCAL_PATH)) {
    const content = readFileSync(ENV_LOCAL_PATH, "utf-8");
    content.split("\n").forEach((line) => {
      const match = line.match(/^([A-Z_][A-Z0-9_]*)="?(.*?)"?$/);
      if (match) {
        existingVars[match[1]] = match[2];
      }
    });
  }

  // Merge: secrets do SM + variáveis locais existentes (locais têm prioridade)
  const merged = { ...secrets, ...existingVars };

  // Gerar .env.local
  const header = "# AUTO-GENERATED by scripts/load-secrets-env.ts — NÃO EDITAR MANUALMENTE\n";
  const lines = Object.entries(merged)
    .map(([key, value]) => `${key}="${value}"`)
    .join("\n");

  writeFileSync(ENV_LOCAL_PATH, header + lines + "\n", { mode: 0o600 });
  console.log(`[pre-build] ${Object.keys(merged).length} variáveis salvas em .env.local`);
}

main().catch((err) => {
  console.error("[pre-build] Erro:", err.message);
  process.exit(1);
});
